---
profile: "develop"

enable:
  rabbitmq: true
  ping: false
  # resourceManager: false
  # predefinedKey: false

broker:
  version: 0.2.4 # deprecated
  server:
    ip: 127.0.0.1
    port: 7000
  UseRedirectURL: false
  UseTLS: false
  webhook:
    token: 7c35ced827cea3da8438e7bbf9214d56

vim:
  server:
    ip: 127.0.0.1
    port: 6000

mariadb:
  host: 127.0.0.1
  port: 3306
  username: 'root'
  password: 'testmaria'
  dbname: 'edge'

cemanager:
  server:
    ip: ce-framework.namespace
    port: 10201

rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: user
  password: 'password!'
  queue:
    vim: vim.queue
    broker: broker.queue
  exchange:
    vim: vim.exchange
    broker: broker.exchange
  route: route

prometheus:
  server:
    ip: 127.0.0.1
    port: 9090

jwt:
  enabled: false
  secret: broker-jwt

---