apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "crawler.fullname" . }}
  labels:
    app: crawler
spec:
  schedule: "{{ .Values.cronJob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: TZ
                  value: Asia/Seoul
                - name: NEWS_PAGE_NUMBER
                  value: {{ quote .Values.crawler.page }}
                - name: EDGE_ROBOTSTXT_OBEY
                  value: {{ quote .Values.crawler.robotObey }}
                - name: EDGE_LOG_LEVEL
                  value: {{ .Values.crawler.log.level }}
                - name: EDGE_CONCURRENT_REQUESTS_PER_DOMAIN
                  value: {{ quote .Values.crawler.concurrentRequest }}
                - name: EDGE_DOWNLOAD_DELAY
                  value: {{ quote .Values.crawler.delay }}
                - name: EDGE_FEED_EXPORT_ENCODING
                  value: {{ .Values.crawler.encoding }}
                - name: ELASTICSEARCH_PROTOCOL
                  value: {{ .Values.elastic.protocol }}
                - name: ELASTICSEARCH_HOST
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.secret.name }}
                      key: host
                - name: ELASTICSEARCH_PORT
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.secret.name }}
                      key: port
                - name: ELASTICSEARCH_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.secret.name }}
                      key: username
                - name: ELASTICSEARCH_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.secret.name }}
                      key: password
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
