{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: gigamec-mano
data:
  application.yml: |-
{{ .Files.Get .Values.configMap.files | indent 4 }}
{{- end }}