{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Release.Namespace }}
data:
  application.yml: |-
{{ .Files.Get .Values.configMap.files | indent 4 }}
{{- end }}
