apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ce-portal.fullname" . }}
  labels:
    {{- include "ce-portal.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ce-portal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ce-portal.selectorLabels" . | nindent 8 }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      {{/*nodeName: mec02*/}}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "ce-portal.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Chart.Name }}
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.configMap.enabled }}
          volumeMounts:
          - name: {{ .Values.localtime.volumeName }}
            mountPath: {{ .Values.localtime.mountPath }}
          - name: {{ .Values.configMap.volumeName }}
            mountPath: {{ .Values.configMap.mountPath }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.configMap.enabled }}
      volumes:
      - name: {{ .Values.localtime.volumeName }}
        hostPath:
          path: {{ .Values.localtime.hostPath }}
      - name: {{ .Values.configMap.volumeName }}
        configMap:
          name: {{ .Values.configMap.name }}
    {{- end }}
