apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mano-portal.fullname" . }}
  labels:
    {{- include "mano-portal.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mano-portal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mano-portal.selectorLabels" . | nindent 8 }}
    spec:
      nodeName: giga-ansan2
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mano-portal.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: mano-portal
              containerPort: 19090
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.configMap.enabled }}
          volumeMounts:
          - name: localtime
            mountPath: /etc/localtime
          - name: portal-conf
            mountPath: /root/conf
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.configMap.enabled }}
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: portal-conf
        configMap:
          name: {{ .Values.configMap.name }}
      {{- end }}