---
profile: "develop"

enable:
  defaultkubeconfig: true
  rabbitmq: true
  # ping: false
  # predefinedKey: false

broker:
  server:
    ip: 127.0.0.1
    port: "7000"
  UseRedirectURL: false
  UseTLS: false
  webhook:
    token: 7c35ced827cea3da8438e7bbf9214d56

vim:
  server:
    ip: 127.0.0.1
    port: "6000"

rabbitmq:
  host: 127.0.0.1
  username: user
  password: 'password!'
  port: 5672
  consumer: consumer.vim
  queue:
    vim: vim.queue
    broker: broker.queue
  exchange:
    vim: vim.exchange
    broker: broker.exchange
  route: route

# prometheus:
#   server:
#     ip: 127.0.0.1
#     port: 9090
---
