common:
  useSpecifiedConfig: false
  UseMessageQueue: true
  UsePredefinedKey: false
  UsePingTest: false
  UseRscMgr: false

vim:
  server:
    ip: 127.0.0.1
    port: "6000"
  UseDynamicRoute: true

broker:
  server:
    ip: 127.0.0.1
    port: "7000"
  webhook:
    token: 7c35ced827cea3da8438e7bbf9214d56
  UseRedirectURL: false
  UseTLS: false

cemanager:
  server:
    ip: 127.0.0.1
    port: 10201

prometheus:
  server:
    ip: 127.0.0.1
    port: 9090

rabbitmq:
  host: 127.0.0.1
  username: user1
  password: 'password'
  port: 5672
  consumer: consumer.vim
  queue:
    vim: vim.queue
    broker: broker.queue
  exchange:
    vim: vim.exchange
    broker: broker.exchange
  route: route

mariadb:
  host: 127.0.0.1
  username: 'maria'
  password: 'testmaria'
  port: 3306
  dbname: 'edge'
