# Common Functions
common:
  useSpecifiedConfig: false
  UseMessageQueue: true
  UsePredefinedKey: false
  UsePingTest: false
  UseRscMgr: false

# VIM Driver specific configs
vim:
  server:
    ip: 127.0.0.1
    port: "6000"
  UseDynamicRoute: true

# BROKER specific configs
broker:
  server:
    ip: 127.0.0.1
    port: "7000"
  webhook:
    token: 7c35ced827cea3da8438e7bbf9214d56
  UseRedirectURL: false
  UseTLS: false

# rsc_mgr specific configs
# rsc_mgr.server.ip: localhost
# rsc_mgr.server.port: 7500

# CE Manager specific configs
cemanager:
  server:
    ip: 127.0.0.1
    port: 10201

# Prometheus specific configs
prometheus:
  server:
    ip: 127.0.0.1
    port: 9090

# AMQP RabbitMQ specific configs
rabbitmq:
  host: 127.0.0.1
  username: mec1
  password: '!mecuser1'
  port: 5672
  queue_vim: CE-VIM
  queue_broker: CE-BROKER
  queue_rscmgr: CE-RSCMGR
  exchange_vim: CE-VIM.exchange
  exchange_broker: CE-BROKER.exchange
  exchange_rscmgr: CE-RSCMGR.exchange
  route: route

# MariaDB specific configs
mariadb:
  host: 127.0.0.1
  username: 'maria'
  password: 'testmaria'
  port: 3306
  dbname: 'mano_rsc'
