replicaCount: 1

image:
  repository: markruler/service-bus
  pullPolicy: Always

nameOverride: ""

fullnameOverride: ""

hostNetwork: false

configMapName: "configmap-service-bus"
configFilesApp: "files/service-bus.yaml"

service:
  name: service-bus
  type: ClusterIP
  port: 7000
  targetPort: 7000
  nodePort: {}

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: ce-api-gateway.default
    # - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # limits:
  #   cpu: 200m
  #   memory: 512Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

rbac:
  create: true

serviceAccount:
  create: true
  name: "sa-service-bus"
  imagePullSecrets: []

securityContext:
  enabled: false
  runAsUser: 65534
  fsGroup: 65534

podSecurityPolicy:
  enabled: false
  annotations: {}

nodeSelector: {}

affinity: {}
# affinity:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: worker
#           operator: In
#           values:
#           - cpu

tolerations: []
