# Default values for mano-vim.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mec01:5000/mec-vim
  tag: 0.2.3
  pullPolicy: Always

nameOverride: ""

fullnameOverride: ""

hostNetwork: false

configMapName: "configmap-vim"
configFilesApp: "files/mec-app.conf"
# configFilesKube: "files/config"

service:
  type: ClusterIP
  port: 6000
  targetPort: 6000
  nodePort: {}

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: worker
            operator: In
            values:
            - cpu

rbac:
  # If true, create & use RBAC resources
  create: true

serviceAccount:
  # Specifies whether a ServiceAccount should be created, require rbac true
  create: true
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name:
  # Reference to one or more secrets to be used when pulling images
  # ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  imagePullSecrets: []

securityContext:
  enabled: false
  runAsUser: 65534
  fsGroup: 65534

podSecurityPolicy:
  enabled: false
  annotations: {}