kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.configMapName }}
  namespace: {{ .Release.namespace }}
data:
{{- if .Values.configFilesApp }}
  service-bus.yaml: |-
{{ .Files.Get "files/service-bus.yaml" | indent 4 }}
{{ end }}
