version: "2.2"

services:

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - ELASTICSEARCH_USERNAME=elastic # default: changeme
      - ELASTICSEARCH_PASSWORD=elastic # default: elastic
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - ELASTICSEARCH_USERNAME=elastic # default: changeme
      - ELASTICSEARCH_PASSWORD=elastic # default: elastic
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data02:/usr/share/elasticsearch/data
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:7.11.2
    container_name: kib01
    depends_on:
      - es01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200"]'
      ELASTICSEARCH_USERNAME: elastic # default: changeme
      ELASTICSEARCH_PASSWORD: elastic # default: elastic
    networks:
      - elastic

  crawler:
    container_name: crawler
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - es01
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
