{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "api-gateway.fullname" . }}
  namespace: {{ .Release.namespace }}
  labels:
    app: {{ template "api-gateway.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  - services/proxy
  - services/finalizers
  - endpoints
  verbs:
  - get
{{- end }}
