---
profile: "develop"

enable:
  defaultkubeconfig: false
  rabbitmq: false
  # ping: false
  # predefinedKey: false

apigw:
  server:
    ip: 127.0.0.1
    port: 6000
  UseRedirectURL: false
  UseTLS: false
  webhook:
    token: 7c35ced827cea3da8438e7bbf9214d56

svcbus:
  server:
    ip: 127.0.0.1
    port: 7000

rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: user
  password: 'password!'
  consumer: consumer.svcbus
  queue:
    svcbus: svcbus.queue
    apigw: apigw.queue
  exchange:
    svcbus: svcbus.exchange
    apigw: apigw.exchange
  route: route

# prometheus:
#   server:
#     ip: 127.0.0.1
#     port: 9090
---
