apiVersion: v1
appVersion: 19.9.0
description: Kubernetes Operational View - read-only system dashboard for multiple
  K8s clusters
engine: gotpl
home: https://github.com/hjacobs/kube-ops-view
icon: https://raw.githubusercontent.com/hjacobs/kube-ops-view/master/kube-ops-view-logo.png
keywords:
- kubernetes
- dashboard
- operations
maintainers:
- email: henning@jacobs1.de
  name: hjacobs
name: kube-ops-view
sources:
- https://github.com/hjacobs/kube-ops-view
version: 1.1.4
